-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
use IEEE.NUMERIC_STD.ALL;

entity DIG_LUT_OpcodeCL is
  port (
    n0: in std_logic;
    n1: in std_logic;
    n2: in std_logic;
    n3: in std_logic;

    p_out: out std_logic_vector (12 downto 0)
);
end DIG_LUT_OpcodeCL;

architecture Behavioral of DIG_LUT_OpcodeCL is
  type mem is array ( 0 to 15) of std_logic_vector (12 downto 0);
  constant my_lut : mem := (
    "0000000101000", "1000000101000", "0000000000000", "0000000000000", 
    "0010011001100", "0010100110100", "0000000000000", "0000000000000", 
    "0110110100000", "0110110100001", "0110110100010", "0110110100011", 
    "0000000000000", "0000000000000", "0000000000000", "0000000000000"
    );
  signal temp : std_logic_vector(3 downto 0);
begin
  temp <= n3 & n2 & n1 & n0;
  p_out <= my_lut(to_integer(unsigned(temp)));
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_2 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_2;

architecture Behavioral of MUX_GATE_BUS_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_1 is
  port (
    p_out: out std_logic;
    sel: in std_logic;
    
    in_0: in std_logic;
    in_1: in std_logic );
end MUX_GATE_1;

architecture Behavioral of MUX_GATE_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    INST: in std_logic_vector(15 downto 0);
    FL_Z: in std_logic;
    ALUOP: out std_logic_vector(1 downto 0);
    RS1: out std_logic_vector(2 downto 0);
    RS2: out std_logic_vector(2 downto 0);
    WS: out std_logic_vector(2 downto 0);
    STR: out std_logic;
    WE: out std_logic;
    DMUX: out std_logic_vector(1 downto 0);
    LDR: out std_logic;
    FL_EN: out std_logic;
    HE: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(2 downto 0);
  signal s1: std_logic_vector(2 downto 0);
  signal s2: std_logic_vector(2 downto 0);
  signal s3: std_logic_vector(3 downto 0);
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic_vector(12 downto 0);
  signal s9: std_logic_vector(1 downto 0);
  signal s10: std_logic_vector(2 downto 0);
  signal s11: std_logic_vector(1 downto 0);
  signal s12: std_logic_vector(2 downto 0);
  signal s13: std_logic_vector(1 downto 0);
  signal s14: std_logic_vector(1 downto 0);
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
begin
  s20 <= (NOT INST(11) OR FL_Z);
  s0 <= INST(10 downto 8);
  s1 <= INST(6 downto 4);
  s2 <= INST(2 downto 0);
  s3 <= INST(15 downto 12);
  gate0: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 3)
    port map (
      sel => s20,
      in_0 => "000",
      in_1 => s0,
      p_out => WS);
  s4 <= s3(0);
  s5 <= s3(1);
  s6 <= s3(2);
  s7 <= s3(3);
  gate1: entity work.DIG_LUT_OpcodeCL -- OpcodeCL
    port map (
      n0 => s4,
      n1 => s5,
      n2 => s6,
      n3 => s7,
      p_out => s8);
  s13 <= s8(1 downto 0);
  s14 <= s8(3 downto 2);
  s15 <= s8(4);
  s16 <= s8(5);
  s17 <= s8(6);
  s11 <= s8(8 downto 7);
  s9 <= s8(10 downto 9);
  s18 <= s8(11);
  s19 <= s8(12);
  gate2: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 3)
    port map (
      sel => s9,
      in_0 => "000",
      in_1 => s0,
      in_2 => s1,
      in_3 => s2,
      p_out => s10);
  gate3: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 3)
    port map (
      sel => s11,
      in_0 => "000",
      in_1 => s0,
      in_2 => s1,
      in_3 => s2,
      p_out => s12);
  gate4: entity work.MUX_GATE_1
    port map (
      sel => s20,
      in_0 => '0',
      in_1 => s18,
      p_out => FL_EN);
  gate5: entity work.MUX_GATE_1
    port map (
      sel => s20,
      in_0 => '0',
      in_1 => s17,
      p_out => STR);
  gate6: entity work.MUX_GATE_1
    port map (
      sel => s20,
      in_0 => '0',
      in_1 => s16,
      p_out => WE);
  gate7: entity work.MUX_GATE_1
    port map (
      sel => s20,
      in_0 => '0',
      in_1 => s15,
      p_out => LDR);
  gate8: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 2)
    port map (
      sel => s20,
      in_0 => "00",
      in_1 => s14,
      p_out => DMUX);
  gate9: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 2)
    port map (
      sel => s20,
      in_0 => "00",
      in_1 => s13,
      p_out => ALUOP);
  gate10: entity work.MUX_GATE_1
    port map (
      sel => s20,
      in_0 => '0',
      in_1 => s19,
      p_out => HE);
  gate11: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 3)
    port map (
      sel => s20,
      in_0 => "000",
      in_1 => s10,
      p_out => RS1);
  gate12: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 3)
    port map (
      sel => s20,
      in_0 => "000",
      in_1 => s12,
      p_out => RS2);
end Behavioral;
