/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module data_hazard_forwarding (
  input I_3,
  input I_2,
  input I_1,
  input I_0,
  output [1:0] ForwardE
);
  assign ForwardE[0] = ((I_3 & ~ I_1 & I_0) | (I_3 & ~ I_2 & I_0));
  assign ForwardE[1] = (I_2 & I_1);
endmodule
