-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    I_3: in std_logic;
    I_2: in std_logic;
    I_1: in std_logic;
    I_0: in std_logic;
    ForwardE: out std_logic_vector(1 downto 0));
end main;

architecture Behavioral of main is
begin
  ForwardE(0) <= ((I_3 AND NOT I_1 AND I_0) OR (I_3 AND NOT I_2 AND I_0));
  ForwardE(1) <= (I_2 AND I_1);
end Behavioral;
