/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module reg_address_extender (
  input [2:0] IN,
  output [15:0] OUT
);
  assign OUT[2:0] = IN;
  assign OUT[15:3] = 13'b0;
endmodule
