-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    p_IN: in std_logic_vector(2 downto 0);
    p_OUT: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
begin
  p_OUT(2 downto 0) <= p_IN;
  p_OUT(15 downto 3) <= "0000000000000";
end Behavioral;
